version: '3'

services:

  redis_db:
    image: redis
    ports:
      - "6379"

  cube:
    build: .
    env_file: .env
    expose:
      - "4000"
    command: node index.js
    links:
      - redis_db
    ports:
      - "80:4000"