version: '3'

services:

  redis_db:
    image: redis
    ports:
      - "6379"

  cube:
    build: .
    env_file: .env
    expose:
      - "4000"
    command: node index.js
    volumes:
      - ./src/schema:/usr/src/app/schema
      - ./src/package.json:/usr/src/app/package.json
      - ./src/package-lock.json:/usr/src/app/package-lock.json
      - ./src/index.js:/usr/src/app/index.js
      - ./src/dashboard-app:/usr/src/app/dashboard-app
    links:
      - redis_db
    ports:
      - "${CUBEJS_PORT}:4000"
      - 3000:3000
